name: saverecipes
description: A new Flutter application to save cooking recipes

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.4
  mockito: ^5.0.4
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.1

flutter:
  uses-material-design: true